%YAML:1.0

image_height: 480
image_width: 640
use_imu: 0

depth_lower_thr: 0.1
depth_upper_thr: 10.0
max_y_diff: 5

# Calibration
distortion_type: 0  # 0 for undistorted inputs, 1 for radial-tangential: [k1, k2, p1, p2, k3], 2 for equidistant/fisheye:  [k1, k2, k3, k4, 0].
cam0:
  intrinsics: [240.5454, 240.5661, 237.5255,240.9758] # fx, fy, cx, cy
  distortion_coeffs: [-0.0059, 0.00059654, -0.0002894, -0.00042483, 0.00011168]
  T_type: 0           # 0 for Euroc format, the following T is Tbc. 1 for Kalibr format, the following T is Tcb
  T: 
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
cam1:
  intrinsics: [240.5454, 240.5661, 237.5255,240.9758] # fx, fy, cx, cy
  distortion_coeffs: [-0.0059, 0.00059654, -0.0002894, -0.00042483, 0.00011168]
  T_type: 0           
  T: 
  - [1.0, 0.0, 0.0, 0.12]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]


# IMU
# rate_hz: 200
# gyroscope_noise_density: 1.0e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
# gyroscope_random_walk: 1.0e-05       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
# accelerometer_noise_density: 1.0e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
# accelerometer_random_walk: 1.0e-3    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
# g_value: 9.8